version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      time: "18:00"
    target-branch: main
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "18:00"
    target-branch: main
