version: '3.8'

services:
  php:
    image: ghcr.io/blumilksoftware/php:8.0.7.0
    container_name: equipment-manager-php
    working_dir: /application
    volumes:
      - .:/application
    networks:
      - equipment-manager
    restart: unless-stopped

networks:
  equipment-manager:
    driver: bridge
